name: Enigma2

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install gcc-10 & g++-10
      run: |
        sudo apt-get install software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt-get install gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: install python packages
      run: |
        pip install netifaces pyopenssl python-wifi service_identity twisted
    - name: install dev packages
      run: |
        sudo apt-get -q update
        sudo apt-get install linux-libc-dev
        sudo apt-get install git
        sudo apt-get install build-essential
        sudo apt-get install automake
        sudo apt-get install libtool
        sudo apt-get install python-dev
        sudo apt-get install zlib1g-dev
        sudo apt-get install gettext
        sudo apt-get install swig
        sudo apt-get install libgstreamer1.0-dev
        sudo apt-get install libgstreamer-plugins-base1.0-dev
        sudo apt-get install libfreetype6-dev
        sudo apt-get install libsigc++-2.0-dev
        sudo apt-get install libfribidi-dev
        sudo apt-get install libssl-dev
        sudo apt-get install libavahi-client-dev
        sudo apt-get install libjpeg-turbo8-dev
        sudo apt-get install libgif-dev
    - name: build enigma2 dependencies
      run: |
        echo installing libdvbsi++
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/jack2015/libdvbsi.git
        cd libdvbsi
        autoreconf -i
        ./configure
        make
        sudo make install
        popd
        echo installing tuxbox
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/OpenPLi/tuxtxt.git
        cd tuxtxt/libtuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        cd ../tuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        popd
    - name: patch enigma cpp files
      run: |
        sed -i 's/eFatal/eDebug/g' lib/gdi/gfbdc.cpp
    - name: build enigma2
      run: |
        echo compiling enigma2
        autoreconf -i
        ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-textlcd
        make
        python -m compileall .
        echo done!
